### ISSUE TITLE
unit tests for time package

### ISSUE THREAD

**Issue by ParkerGits** [skillrecordings/turbo-playground#19]
Want to start contributing with some unit tests here. Going to start with testing the [time](https://github.com/skillrecordings/turbo-playground/blob/main/packages/time/src/index.ts) package functions as I get comfortable with using Turborepo, then I'm happy to contribute more once I get a feel for it.

**Comment by joelhooks** [comment]
@ParkerGits you should be able to work mostly in the package itself 

```
cd packages/time
pnpm test -- --watch
```

and if you want to run all the tests with turbo run `pnpm test` from the top-level folder

**Comment by joelhooks** [comment]
This is a good package to dig into and should be pretty straightforward for testing!

**Comment by ParkerGits** [comment]
1) are these functions expecting negative inputs? or would throwing an error be appropriate for negative inputs.
2) wondering if omitting seconds is intended [for this case of `convertTimeWithTitles`](https://github.com/skillrecordings/turbo-playground/commit/7f30fecd6deaaf11c5b3ba207e4d5af7be4f2265#diff-0653797a5b49296b4a86e49e8c577168332c8bdfbc9d92ead8b1f20b891650d0R61)

**Comment by ParkerGits** [comment]
negative inputs to these functions now give the same output as inputs of zero.

I suppose then a better test would be "negative inputs give the same output as inputs of zero" in case someone were to come in and make changes.
