### ISSUE TITLE
migrate compilersforhumans into monorepo

### ISSUE THREAD

**Issue by joelhooks** [skillrecordings/turbo-playground#32]
the compilersforhumans project is currently in a private repository and needs to be migrated into this monorepo

**Comment by joelhooks** [comment]
it'd be nice if this was done in staged commits so that the actual process and changes got documented step by step in the PR commits

**Comment by zacjones93** [comment]
I'd be down to give this a crack, I'm excited to get familiar with turbo. 

I couldn't locate compilersforhumans so I might not have access to the project
